name: 🐛 Bug Report
description: Report a bug or issue with a supported device
title: "[Bug] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # 🐛 Bug Report
        
        Thank you for reporting a bug! This template is for issues with **already supported devices** that are not working correctly.
        
        ## 📋 When to use this template:
        - ✅ Your device model is **listed** in our [supported devices](https://github.com/domalab/ha-philips-airpurifier#-supported-devices)
        - ✅ The device was working before but now has issues
        - ✅ The device integration loads but some features don't work
        - ✅ You're getting error messages in Home Assistant logs
        
        ## ❌ When NOT to use this template:
        - 🚫 **Device Support**: Your device model is not supported → Use "Device Support Request" template
        - 🚫 **Feature Requests**: Want new features for supported devices → Use "Feature Request" template

  - type: input
    id: device_model
    attributes:
      label: 📱 Device Model
      description: "Your Philips device model (must be from supported list)"
      placeholder: "AC2729/10"
    validations:
      required: true

  - type: dropdown
    id: bug_category
    attributes:
      label: 🏷️ Bug Category
      description: "What type of issue are you experiencing?"
      options:
        - "Device not discovered/detected"
        - "Connection issues (frequent disconnects)"
        - "Incorrect sensor readings"
        - "Controls not working (fan speed, modes, etc.)"
        - "Custom services not working"
        - "Integration fails to load"
        - "Home Assistant crashes/errors"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: 📝 Bug Description
      description: "Clear description of what's wrong and what you expected to happen"
      placeholder: |
        **What's happening:**
        The fan speed control doesn't work - when I change speed in HA, nothing happens on the device.
        
        **What should happen:**
        The device should change fan speed when I adjust it in Home Assistant.
        
        **When did this start:**
        After updating to version X.X.X
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: "Step-by-step instructions to reproduce the issue"
      placeholder: |
        1. Open Home Assistant
        2. Go to the air purifier entity
        3. Change fan speed from Auto to Speed 2
        4. Observe that device doesn't change speed
      render: markdown
    validations:
      required: true

  - type: input
    id: integration_version
    attributes:
      label: 📦 Integration Version
      description: "Version of the Philips Air Purifier integration"
      placeholder: "v0.27.0"
    validations:
      required: true

  - type: input
    id: ha_version
    attributes:
      label: 🏠 Home Assistant Version
      description: "Your Home Assistant version"
      placeholder: "2025.6.0"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Relevant Logs
      description: |
        Home Assistant logs related to the issue. Enable debug logging first:
        
        ```yaml
        logger:
          logs:
            custom_components.philips_airpurifier_coap: debug
            coap: debug
            aioairctrl: debug
        ```
      placeholder: |
        ```
        2025-06-11 10:30:00 ERROR (MainThread) [custom_components.philips_airpurifier] ...
        ```
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: 📝 Additional Context
      description: "Any other relevant information"
      placeholder: |
        - Network setup details
        - Recent changes to your setup
        - Workarounds you've tried
        - Screenshots if applicable
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: "Please confirm you have done the following:"
      options:
        - label: "I have checked that my device is in the [supported devices list](https://github.com/domalab/ha-philips-airpurifier#-supported-devices)"
          required: true
        - label: "I have searched existing issues to make sure this isn't a duplicate"
          required: true
        - label: "I have tried restarting Home Assistant"
          required: false
        - label: "I have tried power cycling the device"
          required: false
        - label: "I have enabled debug logging and included relevant logs"
          required: false
