name: ✨ Feature Request
description: Suggest a new feature or enhancement for supported devices
title: "[Feature] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # ✨ Feature Request
        
        Thank you for suggesting a new feature! This template is for requesting **new features or enhancements** for already supported devices.
        
        ## 📋 When to use this template:
        - ✅ Your device model is **already supported** by the integration
        - ✅ You want to add new functionality or improve existing features
        - ✅ You have ideas for better automation or control options
        - ✅ You want to suggest UI/UX improvements
        
        ## ❌ When NOT to use this template:
        - 🚫 **Device Support**: Your device model is not supported → Use "Device Support Request" template
        - 🚫 **Bug Reports**: Existing features are broken → Use "Bug Report" template

  - type: dropdown
    id: feature_category
    attributes:
      label: 🏷️ Feature Category
      description: "What type of feature are you requesting?"
      options:
        - "New entity type (sensor, switch, etc.)"
        - "Enhanced custom service"
        - "New custom service"
        - "Improved automation capabilities"
        - "Better device discovery"
        - "UI/UX improvements"
        - "Performance optimization"
        - "Configuration options"
        - "Documentation improvement"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: 📝 Feature Description
      description: "Clear description of the feature you'd like to see"
      placeholder: |
        **What feature would you like:**
        Add a sensor that shows the estimated remaining filter life in days instead of just percentage.
        
        **Why would this be useful:**
        It would help users plan filter replacements better and set up more meaningful automations.
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: 🎯 Use Case / Problem Solved
      description: "What problem does this feature solve? How would you use it?"
      placeholder: |
        **Problem:**
        Currently I can only see filter life as a percentage, but I don't know how many days that translates to.
        
        **Use Case:**
        I want to create an automation that orders new filters when there are 30 days of life remaining.
        
        **Benefit:**
        This would make maintenance planning much easier for users.
      render: markdown
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: 💡 Proposed Solution
      description: "How do you think this feature should work?"
      placeholder: |
        **Implementation idea:**
        - Add a new sensor entity: `sensor.device_filter_days_remaining`
        - Calculate based on current usage patterns and filter life percentage
        - Update daily or when filter percentage changes
        
        **UI/UX:**
        - Show in device card alongside existing filter percentage
        - Include in device diagnostics
      render: markdown
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: "Have you considered any alternative solutions or workarounds?"
      placeholder: |
        **Current workarounds:**
        - Manual calculation based on usage patterns
        - Using template sensors in Home Assistant
        
        **Why they're not ideal:**
        - Requires manual maintenance
        - Not accurate for varying usage patterns
      render: markdown
    validations:
      required: false

  - type: input
    id: affected_devices
    attributes:
      label: 📱 Affected Device Models
      description: "Which device models would benefit from this feature?"
      placeholder: "All air purifiers / AC2729, AC3858 / All devices with filters"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority Level
      description: "How important is this feature to you?"
      options:
        - "Low - Nice to have"
        - "Medium - Would improve my experience"
        - "High - Significantly impacts usability"
        - "Critical - Blocking important use cases"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution
      description: "Would you be willing to help implement this feature?"
      options:
        - label: "I'm willing to test development versions"
        - label: "I can help with documentation"
        - label: "I have programming skills and could contribute code"
        - label: "I can provide detailed requirements and feedback"

  - type: textarea
    id: additional_context
    attributes:
      label: 📝 Additional Context
      description: "Any other relevant information, mockups, or examples"
      placeholder: |
        - Screenshots or mockups of desired UI
        - Examples from other integrations
        - Technical considerations
        - Related feature requests
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: "Please confirm you have done the following:"
      options:
        - label: "I have searched existing issues to make sure this isn't a duplicate"
          required: true
        - label: "This feature request is for already supported devices"
          required: true
        - label: "I have clearly described the problem this feature would solve"
          required: true
